/**
 * TwilioController: Express routes for Twilio webhooks + WebSocket upgrade.
 *
 * Routes:
 *   POST /webhooks/twilio/voice   — Returns TwiML to open a Media Stream
 *   POST /webhooks/twilio/status  — Call status callbacks (answered, completed, …)
 *   POST /calls/outbound          — Internal API: initiate an outbound call
 *   GET  /health                  — Health check
 *
 * WebSocket:
 *   /stream  — Twilio calls this path to open the bidirectional audio stream
 */

import { Request, Response, Router } from 'express';
import WebSocket from 'ws';
import { Env } from '../../config';
import { Logger } from '../../shared/Logger';
import { TwilioService } from './TwilioService';
import { TwilioOutboundCallRequest } from './TwilioTypes';
import { MediaGatewayService } from '../media-gateway/MediaGatewayService';

const log = Logger.root('TwilioController');

// ─── TwiML Helpers ────────────────────────────────────────────────────────────


function twimlStreamResponse(streamUrl: string, callerNumber: string): string {
  // IMPORTANT: No <Say> before <Connect>.
  //
  // A <Say> before <Connect><Stream> delays the WebSocket connection until TTS finishes
  // (5–10 seconds), then Nova needs another 2–5 s to bootstrap — caller hears 15+ seconds
  // of silence before any AI audio. Nova Sonic generates its own greeting via
  // NovaAudioStreamer.startConversation(), so any pre-stream TTS creates a duplicate
  // greeting and kills perceived latency.
  //
  // The Nova greeting is generated by NovaAudioStreamer.startConversation() the moment
  // the WebSocket connects (~2–4 s from call answer). That is the only greeting the
  // caller should hear.
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<Response>',
    '  <Connect>',
    `    <Stream url="${streamUrl}">`,
    `      <Parameter name="callerNumber" value="${callerNumber}"/>`,
    '    </Stream>',
    '  </Connect>',
    '</Response>',
  ].join('\n');
}

// ─── Router ───────────────────────────────────────────────────────────────────

export function createTwilioRouter(
  twilioService: TwilioService,
  mediaGateway: MediaGatewayService,
): Router {
  const router = Router();

  // ── Inbound / Outbound Call Voice Webhook ──────────────────────────────────
  // Twilio POSTs here when a call is answered. We return TwiML to open a stream.

  router.post('/webhooks/twilio/voice', (req: Request, res: Response): void => {
    const callSid: string = req.body?.CallSid ?? '';
    const callerNumber: string = req.body?.From ?? '';
    const direction: string = req.body?.Direction ?? 'inbound';

    log.info('Twilio voice webhook', { callSid, callerNumber, direction });

    if (!callSid) {
      res.status(400).send('Missing CallSid');
      return;
    }

    // Construct the WebSocket URL for the media stream.
    //
    // Prefer TWILIO_WEBHOOK_BASE_URL (which we know Twilio can reach — we used it
    // to create the call) over req.headers.host (which can be wrong behind
    // proxies, tunnels, or load balancers).
    //
    // Convert https:// → wss:// (or http:// → ws://) and append /stream.
    let streamUrl: string;
    const baseUrl = Env.twilio.webhookBaseUrl;
    if (baseUrl) {
      streamUrl = baseUrl.replace(/^https?:\/\//, (m) => m === 'https://' ? 'wss://' : 'ws://') + '/stream';
    } else {
      // Fallback: derive from Host header (less reliable behind proxies).
      const host = req.headers.host ?? 'localhost';
      streamUrl = `wss://${host}/stream`;
    }

    log.info('Returning TwiML with media stream', { callSid, streamUrl });
    res.type('text/xml').send(twimlStreamResponse(streamUrl, callerNumber));
  });

  // ── Call Status Callback ───────────────────────────────────────────────────

  router.post('/webhooks/twilio/status', (req: Request, res: Response): void => {
    const callSid: string = req.body?.CallSid ?? '';
    const callStatus: string = req.body?.CallStatus ?? '';
    // Twilio includes ErrorCode/ErrorMessage on failed/canceled calls — surface them.
    const errorCode = req.body?.ErrorCode;
    const errorMessage = req.body?.ErrorMessage;

    if (errorCode || callStatus === 'failed') {
      log.warn('Twilio call FAILED — see Twilio error code', {
        callSid,
        callStatus,
        errorCode,
        errorMessage,
        hint: 'Common: 21215/13227 geo-permission (enable India/+91 in Voice Geo Permissions); 21219/13225 unverified number (trial can only call Verified Caller IDs); 21210 invalid From number.',
      });
    } else {
      log.info('Twilio status callback', { callSid, callStatus });
    }

    res.status(204).send();

    if (['completed', 'failed', 'busy', 'no-answer', 'canceled'].includes(callStatus)) {
      mediaGateway.handleCallEnded(callSid, callStatus).catch((err) => {
        log.error('Error handling call end from status callback', err as Error);
      });
    }
  });

  // ── Outbound Call API ──────────────────────────────────────────────────────

  router.post('/calls/outbound', async (req: Request, res: Response): Promise<void> => {
    const { to, from, metadata } = req.body as Partial<TwilioOutboundCallRequest>;

    if (!to) {
      res.status(400).json({ error: 'Missing required field: to' });
      return;
    }

    const result = await twilioService.initiateOutboundCall({ to, from, metadata });

    if (result.status === 'failed') {
      res.status(502).json({ error: result.message });
      return;
    }

    res.status(202).json(result);
  });

  // ── Health ─────────────────────────────────────────────────────────────────

  router.get('/health', (_req: Request, res: Response): void => {
    res.json({
      status: 'ok',
      activeSessions: mediaGateway.activeSessionCount(),
      activeStreams: twilioService.activeStreamCount(),
      timestamp: new Date().toISOString(),
    });
  });

  return router;
}

// ─── WebSocket Upgrade Handler ────────────────────────────────────────────────

/**
 * Called by WebSocketServer when Twilio upgrades a connection to /stream.
 */
export function handleTwilioStreamUpgrade(
  ws: WebSocket,
  remoteAddress: string,
  twilioService: TwilioService,
): void {
  log.info('Twilio media stream WebSocket connected', { remoteAddress });
  twilioService.acceptStream(ws, remoteAddress);
}
